### ISSUE TITLE
240p mode

### ISSUE THREAD

**Issue by ghost** [raz0red/wii7800#4]
hello mate

please could you add 240p mode (double strike) 

and also ability to disable bilinear filtering

thank you for listening

**Comment by raz0red** [comment]
At some point, would really like to do this. Should just require integrating the video changes I made in WiiMednafen. Now that I have it building with the latest devkitPro, it should be fairly straight-forward.

**Comment by raz0red** [comment]
I am going to look at adding this to the next release (0.5)

**Comment by raz0red** [comment]
Making good progress on this. I should have a test build in the next couple of days. Please let me know if anyone is interested in helping to test this release.

Thanks!

**Comment by raz0red** [comment]
Fixed in 0.5

**Comment by ghost** [comment]
Thanks a lot for your hard work. I will test next week when I'm back at my house!!! Long live Atari 7800

**Comment by raz0red** [comment]
No problem, sorry it took so long... 

Also, if you are interested in helping test another Atari 7800 related project, please let me know. Thanks!

**Comment by ghost** [comment]
Yes I am happy to test. Please let me know. Do you have a 5200 or 800xl emulator too? I wish someone would make good spectrum and c64 emulators for the Wii
