### ISSUE TITLE
Tower Toppler game doesn't work...

### ISSUE THREAD

**Issue by SieKensou** [raz0red/wii7800#5]
I noticed this game doesn't work... do you know why and if it is possible to fix it?
Thanks.

P.S.: Do you have some future plans for this emulator?

**Comment by clobber** [comment]
>I noticed this game doesn't work

Yes it does. If using wii7800 v0.3, you need the "overdump" ROM of this game. If you are using a version of wii7800 that you built from source that includes my fixes, you can use both the good dump of the game or the "overdump" (bad) version.

**Comment by SieKensou** [comment]
Thanks for the reply. I'm using Wii7800 v0.3 (USB version). You are right, the overdump rom works fine, thanks.
Is there a link of that version with all your fixes? Why that fixes are not added to the official version?

**Comment by clobber** [comment]
>Is there a link of that version with all your fixes?

No, not that I am aware of.

>Why that fixes are not added to the official version?

This is a very old project that @raz0red no longer maintains and he has probably retired from working on this stuff. The last release was 7 years ago and the Wii is ancient hardware at this point. I merely submitted patches for the sake of posterity for anyone else that uses a fork of ProSystem.

**Comment by SieKensou** [comment]
Okay, thanks for the info. It would be great if @raz0red could just take a look to add that patches and other possible small fixes. It shouldn't take too much time. I think a lot of people still uses Wii (myself for example) and I prefer this full emulators more than retroarch and that kind of multi-emulators. It would be great if the autor of this emulator or other person with good knowledge of the Atari 7800 and the Wii could continue a bit making this emulator even better (showing a preview screenshot when selecting the game would be a great add).
Anyway I really thank raz0red for the great job he did porting this emulator. And thank you clobber for let me a way to play Tower Toppler :)

**Comment by raz0red** [comment]
Just committed some code to master that supports building with the latest devkitPro. I need to do quite a bit more testing. However, once completed, I will release a new version that includes all of the changes that have been submitted (including the great enhancements by clobber).

**Comment by SieKensou** [comment]
That's great! Thanks for that fixes, I hope we can see a new version soon (and I hope you can add support for preview screenshots when you are selecting a game).

**Comment by raz0red** [comment]
Fixed in the 0.4 release
