### ISSUE TITLE
Add USB Support

### ISSUE THREAD

**Issue by raz0red** [raz0red/wii7800#8]
Looking to add this to the next release (0.5)

**Comment by SieKensou** [comment]
Great! This emulator really needs USB support.
I had 0.3 version and I used it through USB, but I don't know who implemented it.

**Comment by raz0red** [comment]
Yeah, my goal is to add all of the features that were in my more recent emulators. That includes USB support and the various video modes (including 240p). Not sure I will add SMB support, but it is a possibility.

**Comment by niuus** [comment]
Thanks for the update, raz0red! I am finally enjoying Atari 7800 games after many years, with my Wii U Pro Controller! It's really cool that you're planning to add 240p support too. Will Wii U Pro controller support be reaching WiiMednafen too?

**Comment by raz0red** [comment]
> Thanks for the update, raz0red! I am finally enjoying Atari 7800 games after many years, with my Wii U Pro Controller! It's really cool that you're planning to add 240p support too. Will Wii U Pro controller support be reaching WiiMednafen too?

Ha! Sorry for taking so long...
It should be pretty easy to add support for WiiMednafen. If you want to submit an issue in the WiiMednafen GitHub repository, I can probably put together a quick build for you to test.

Thanks!

**Comment by niuus** [comment]
> Ha! Sorry for taking so long...
> It should be pretty easy to add support for WiiMednafen. If you want to submit an issue in the WiiMednafen GitHub repository, I can probably put together a quick build for you to test.

Sure! Thanks again, raz0red.

**Comment by raz0red** [comment]
Fixed in 0.5
